default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    username: postgres
    password: postgres
    host: localhost
    port: 5432
development:
    <<: *default
    database: practice_dev
test:
    <<: *default
    database: practice_test
production:
    <<: *default
    database: practice_prod
